#!/usr/bin/env bash
#Install your load balancer

apt update
apt install -y haproxy=1.6.\*

printf %s "
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
    balance roundrobin
    server 28524-web-01 34.231.109.250 check
    server 28524-web-02 34.204.168.214 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
